#! /bin/sh
# Usage:
# $ curl -sL git@github.com:oomija-ts/git_hooks.git/git_hooks_install | sh

if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  cd `pwd`/`git rev-parse --show-cdup`
fi

hook_files="utils pre-commit"
for file_name in $hook_files
do
  dst=".git/hooks/$file_name"
  curl -L -O https://gist.github.com/kei-p/c00972b403e467f952c6e74bee9774ad/raw/$file_name > $dst 2> /dev/null
  chmod +x $dst
  echo "install $dst"
done
